### ISSUE TITLE
Fortune and Tags

### ISSUE THREAD

**Issue by BioMasterZap** [Kamorzy/Amethyst-Tools#1]
I was testing the mod (v1.0 for Fabric 1.20.4) and noticed a couple minor things that I thought were worth mentioning. The one that is probably unintended is that the Amethyst Hoe does not seem to be tagged as a hoe while the other tools are tagged.

The other might be intended behavior, but Budding Amethyst are unaffected by Fortune. You can use Silk Touch to harvest the Amethyst Clusters, so it felt kind of bad to break a Budding Amethyst with Fortune 3 and still get the same 0-1 as without enchants. I made a data pack change it to scale with Fortune and it went from 0.46 Amethyst Clusters per Budding Amethyst to 1.2 with Fortune 3, which seems pretty reasonable. Here is the budding_amethyst.json I used based on yours with the fortune section from diamond ore.
https://gist.github.com/BioMasterZap/fb5bab9dcf7d5bf8415158537a92a605

Also, this will come down to a preference thing, but I wanted to suggest changing the Sword's Damage from 7 to 6.5 (or 3 to 2.5). Currently, it offers the same damage as a Diamond Sword while being nearly twice as enchantable, so the only drawback is it has 500 less durability. The tools could be a mining speed of 7 instead of 7.5 to better sit between Iron (6) and Diamond (8), but they are still a bit slower than diamond and 1 Mining Level lower so you'll still need Diamond for Obsidian and Netherite. But for the sword, it feels like Amethyst can kinda replace Diamond until you are able to upgrade to Netherite. If you prefer keep it as is, I'll probably look into tweaking the attributes for my pack, but it seems attributes aren’t as easy to modify with data packs or the like so I thought I'd bring it up.

**Comment by Kamorzy** [comment]
Sorry for the delay. I was busy irl and didn't notice this. Those are all reasonable suggestions and some that I was thinking as well (the stat changes). The hang up I have is that enchanted diamond tools are so easy to get with villager trades, that I felt amethyst already perhaps didn't have enough draw to it as it is. I typically get access to solid enchanted diamond villager trades before I even find a geode in my worlds.

But I think I'll incorporate them anyways. It makes sense that the base stats should be distinctly worse than diamond, and I have another idea to give it a distinct purpose that isn't just making it more similar to diamond performance. Thank you for the suggestions.

**Comment by Kamorzy** [comment]
Completed and uploaded to Modrinth
